#!/bin/sh
node common/scripts/install-run-rush.js prettier || exit $?
node common/scripts/install-run-rush-pnpm.js run type:check || exit $?
node common/scripts/install-run-rush-pnpm.js run lint:staged || exit $?